backend:
  name: github
  repo: ghostsignalstudios-svg/ghostsignalsite
  branch: main
  base_url: https://ghostsignalstudios.com
  auth_endpoint: api/auth

media_folder: "GhostsignalstudiosWebsite/images/uploads"
public_folder: "/images/uploads"

site_url: https://ghostsignalstudios.com

collections:
  - name: "blog"
    label: "Blog"
    folder: "GhostsignalstudiosWebsite/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tag", widget: "string", default: "Gaming" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
